service: aws-api-usage-plan
provider:
  name: aws
  runtime: nodejs12.x
  usagePlan:
    - silver:
        quota:
          limit: 10
          period: DAY
        throttle:
          burstLimit: 1
          rateLimit: 1
    - gold:
        quota:
          limit: 20
          period: DAY
        throttle:
          burstLimit: 2
          rateLimit: 2
    - platinum:
        quota:
          limit: 100
          period: DAY
        throttle:
          burstLimit: 12
          rateLimit: 10       
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          authorizer: aws_iam
          private: true